# Generated by Django 6.0.5 on 2026-05-28 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateEntryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expected_time', models.TimeField()),
                ('actual_time', models.TimeField()),
                ('late_minutes', models.IntegerField()),
                ('grace_minutes', models.IntegerField(default=10)),
                ('is_penalized', models.BooleanField(default=False)),
                ('penalty_type', models.CharField(blank=True, choices=[('half_day_deduction', 'Half Day Deduction'), ('salary_deduction', 'Salary Deduction'), ('warning', 'Warning')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.branch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_late_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'late_entry_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('club', 'Club Leave'), ('unpaid', 'Unpaid Leave')], max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_session', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='branch.branch')),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('club', 'Club Leave'), ('unpaid', 'Unpaid Leave')], max_length=10)),
                ('year', models.IntegerField()),
                ('total_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_balances',
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('club', 'Club Leave'), ('unpaid', 'Unpaid Leave')], max_length=10)),
                ('annual_quota', models.IntegerField()),
                ('max_club_days', models.IntegerField(default=5)),
                ('carry_forward', models.BooleanField(default=False)),
                ('max_carry_days', models.IntegerField(default=0)),
                ('min_advance_days', models.IntegerField(default=3)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('sandwich_rule', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='branch.branch')),
            ],
            options={
                'db_table': 'leave_policies',
                'unique_together': {('branch', 'leave_type')},
            },
        ),
    ]
