# Generated by Django 6.0.5 on 2026-10-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Unpaid/Casual Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Unpaid/Casual Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('sick', 'Sick Leave'), ('casual', 'Unpaid/Casual Leave')], max_length=10),
        ),
    ]
