# Generated by Django 6.0.5 on 2026-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateentryrecord',
            name='grace_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
