# Generated by Django 6.0.5 on 2026-06-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_branch_name'),
        ('leave', '0005_alter_lateentryrecord_grace_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='branch.branch'),
        ),
    ]
