# Generated by Django 6.0.5 on 2026-06-23 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leaveapplication_branch'),
        ('students', '0004_studentprofile_student_batch_student_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeaveApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave'), ('medical', 'Medical Leave'), ('emergency', 'Emergency Leave'), ('exam', 'Exam Leave'), ('mobile_usage', 'Mobile Usage Permission'), ('uniform', 'Uniform Leave')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField(blank=True, help_text='Leave start time (if applicable)', null=True)),
                ('to_time', models.TimeField(blank=True, help_text='Leave end time (if applicable)', null=True)),
                ('reason', models.TextField(help_text='Reason of Leave')),
                ('is_capable_of_proof', models.BooleanField(default=False, help_text='Is the student able to provide supporting proof for this leave?')),
                ('proof_document', models.FileField(blank=True, help_text='Upload proof document if applicable', null=True, upload_to='leave/student_proof/')),
                ('parent_consulted', models.BooleanField(default=False, help_text='Has the parent been consulted about this leave?')),
                ('parent_signature_date', models.DateField(blank=True, help_text='Date of parent signature on the physical form', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff member who received this leave application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_student_leaves', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_leaves', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='students.student')),
            ],
            options={
                'db_table': 'student_leave_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
