# Generated by Django 6.0.5 on 2026-06-22 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_notificationhistory'),
        ('branch', '0006_alter_branch_name'),
        ('leave', '0006_alter_leaveapplication_branch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='auth_user.organization'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='branch.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('organization', 'date')},
        ),
    ]
