# Generated by Django 6.0.5 on 2026-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_alter_publicholiday_unique_together_and_more'),
        ('leave', '0007_studentleaveapplication'),
    ]

    operations = [
    ]
