# Generated by Django 5.1.1 on 2026-09-10 07:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0006_update_naranpura_coordinates'),
        ('payroll', '0004_payslip_reimbursements_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short title of the expense', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the expense')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount claimed', max_digits=12)),
                ('proof', models.FileField(help_text='Receipt, bill, or supporting document', upload_to='reimbursements/proofs/')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the expense occurred')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False, help_text='True when the corresponding payslip/payroll run has been disbursed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch associated with this expense claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='branch.branch')),
                ('payroll_run', models.ForeignKey(blank=True, help_text='Payroll run in which this reimbursement was included', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='payroll.payrollrun')),
                ('payslip', models.ForeignKey(blank=True, help_text='Payslip in which this reimbursement was credited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='payroll.payslip')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Staff member applying for the expense reimbursement', on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reimbursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
