# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('contact', 'Contact Us'), ('inquiry', 'Inquiry Form')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_student', models.CharField(max_length=15)),
                ('course', models.CharField(blank=True, choices=[('cseet', 'CSEET'), ('cs_executive', 'CS Executive'), ('cs_professional', 'CS Professional')], max_length=20, null=True)),
                ('group_module', models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module')], max_length=20)),
                ('batch_attempt', models.CharField(blank=True, choices=[('june', 'June'), ('oct', 'October'), ('feb', 'February'), ('dec', 'December')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('consent', models.BooleanField(default=False)),
                ('current_stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit', 'Visit'), ('visited', 'Visited'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Latest note added during status update.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateField(blank=True, null=True)),
                ('interested_at', models.DateField(blank=True, null=True)),
                ('followup_set_at', models.DateField(blank=True, null=True)),
                ('converted_at', models.DateField(blank=True, null=True)),
                ('visit_set_at', models.DateField(blank=True, null=True)),
                ('lost_at', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('street', models.TextField(blank=True)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('phone_father', models.CharField(blank=True, max_length=15)),
                ('qualification', models.CharField(blank=True, choices=[('appearing_12', 'Appearing 10+2'), ('pass_12', '10+2 Pass or Equivalent'), ('cseet_pass', 'CSEET Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20)),
                ('reference', models.CharField(blank=True, choices=[('offline_ad', 'Offline Ad'), ('existing', 'Existing Student'), ('social_media', 'Social Media'), ('google', 'Seen on Google'), ('seminar', 'Seminar'), ('none', 'None of the above')], max_length=20)),
                ('inquiry_date', models.DateField(blank=True, null=True)),
                ('tenth_medium', models.CharField(blank=True, choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10)),
                ('tenth_school', models.CharField(blank=True, max_length=200)),
                ('tenth_coaching', models.CharField(blank=True, max_length=200)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenth_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_medium', models.CharField(blank=True, choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10)),
                ('twelfth_school', models.CharField(blank=True, max_length=200)),
                ('twelfth_coaching', models.CharField(blank=True, max_length=200)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grad_university', models.CharField(blank=True, max_length=200)),
                ('grad_college', models.CharField(blank=True, max_length=200)),
                ('grad_last_sem', models.CharField(blank=True, max_length=200)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Counsellor / Sales Executive manually assigned to this lead. Leave null if unassigned — only senior roles can then view it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='branch.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_from', models.ForeignKey(blank=True, help_text='Previous assignee (null if unassigned before).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='New assignee (null means unassigned).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff member who made the assignment change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_assignment_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit', 'Visit'), ('visited', 'Visited'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_stages',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['form_type'], name='leads_form_ty_157298_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['current_stage'], name='leads_current_cd3a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['course'], name='leads_course_11b780_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_created_e6e479_idx'),
        ),
    ]
