# Generated by Django 6.0.5 on 2026-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, help_text='Latest note added during status update.'),
        ),
    ]
