# Generated by Django 6.0.5 on 2026-05-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='phone',
            new_name='phone_student',
        ),
    ]
