# Generated by Django 6.0.5 on 2026-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_phone_lead_phone_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
