# Generated by Django 6.0.5 on 2026-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_group_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_overdue_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_1d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_2h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
