# Generated by Django 6.0.5 on 2026-05-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_inquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='apartment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
