# Generated by Django 6.0.5 on 2026-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_leadtransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reference',
            field=models.CharField(blank=True, choices=[('offline_ad', 'Offline Ad'), ('existing', 'Existing Student'), ('social_media', 'Social Media'), ('google', 'Seen on Google'), ('seminar', 'Seminar'), ('none', 'None of the above'), ('other', 'Other')], max_length=20),
        ),
    ]
