# Generated by Django 6.0.5 on 2026-05-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='current_stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
    ]
