# Generated by Django 6.0.5 on 2026-09-09 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_reference_name_alter_lead_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_daily_activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesActivityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_type', models.CharField(choices=[('start_selfie', 'Start of Day Selfie'), ('start_odometer', 'Start of Day Odometer'), ('end_selfie', 'End of Day Selfie'), ('end_odometer', 'End of Day Odometer'), ('school_interior', 'School Interior'), ('school_exterior', 'School Exterior'), ('exhibition', 'Exhibition')], max_length=30)),
                ('photo', models.ImageField(upload_to='sales/activity_photos/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('odometer_kms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='leads.salesdailyactivity')),
            ],
            options={
                'db_table': 'sales_activity_photos',
                'ordering': ['captured_at', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='salesdailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'activity_date'), name='unique_sales_activity_per_user_day'),
        ),
    ]
