# Generated by Django 6.0.5 on 2026-06-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_contacted_at_lead_converted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
