# Generated by Django 5.1.1 on 2026-09-11 05:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_salesdailyactivity_salesactivityphoto_and_more'),
        ('payroll', '0004_payslip_reimbursements_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdometerReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_kms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('end_kms', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_kms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('expense_per_km', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Reimbursement rate per kilometer (editable by approver)', max_digits=8)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated as total_kms * expense_per_km', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False, help_text='True when the corresponding payslip/payroll run has been disbursed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_reading', to='leads.salesdailyactivity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_odometer_readings', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(blank=True, help_text='Payroll run in which this travel expense was included', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_readings', to='payroll.payrollrun')),
                ('payslip', models.ForeignKey(blank=True, help_text='Payslip in which this travel expense was credited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odometer_readings', to='payroll.payslip')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_odometer_readings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_odometer_readings',
                'ordering': ['-activity__activity_date', '-created_at'],
            },
        ),
    ]
