# Generated by Django 5.1.1 on 2026-09-11 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_odometerreading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDailyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField(default=django.utils.timezone.localdate, help_text='The date this plan is for.')),
                ('description', models.TextField(help_text='Describe what the salesperson plans to do today — schools to visit, targets, events, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_daily_plans',
                'ordering': ['-plan_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The daily plan this activity belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='leads.salesdailyplan'),
        ),
        migrations.AddConstraint(
            model_name='salesdailyplan',
            constraint=models.UniqueConstraint(fields=('user', 'plan_date'), name='unique_sales_plan_per_user_day'),
        ),
    ]
