# Generated by Django 6.0.5 on 2026-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_assigned_to_assignmentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='current_stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit', 'Visit'), ('visited', 'Visited'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadstage',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('visit', 'Visit'), ('visited', 'Visited'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], max_length=20),
        ),
    ]
