# Generated by Django 5.1.1 on 2026-09-12 10:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_add_sales_daily_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdailyplan',
            options={'ordering': ['-plan_date', 'start_time', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='salesdailyplan',
            name='unique_sales_plan_per_user_day',
        ),
        migrations.AddField(
            model_name='odometerreading',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler')], default='2_wheeler', help_text='Type of vehicle used: 2 wheeler (₹5/km) or 4 wheeler (₹12/km)', max_length=20),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of the scheduled event/plan', null=True),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='place',
            field=models.CharField(blank=True, default='', help_text='Location/venue of the plan or event', max_length=255),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='reminder_day_of_event_sent',
            field=models.BooleanField(default=False, help_text='True once the 8:00 AM day-of-event reminder has been sent.'),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='reminder_one_day_before_sent',
            field=models.BooleanField(default=False, help_text='True once the 8:00 AM 1-day-before reminder has been sent.'),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of the scheduled event/plan', null=True),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='type',
            field=models.CharField(blank=True, default='', help_text='Type of event/plan, e.g. School Visit, Seminar, Exhibition, Meeting, Demo', max_length=100),
        ),
        migrations.AlterField(
            model_name='odometerreading',
            name='expense_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Reimbursement rate per kilometer (auto-set based on vehicle_type: ₹5 for 2-wheeler, ₹12 for 4-wheeler)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='salesdailyplan',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Describe what the salesperson plans to do — schools to visit, targets, agenda, etc.'),
        ),
    ]
