# Generated by Django 6.0.5 on 2026-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_salesdailyplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdailyactivity',
            options={'ordering': ['-activity_date', '-created_at', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='salesdailyactivity',
            name='unique_sales_activity_per_user_day',
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Optional name/title for this activity (e.g. 'Morning School Visit', 'Seminar at XYZ College', 'Lead Follow-up'). Useful when multiple activities occur on the same day.", max_length=100),
        ),
    ]
