# Generated by Django 5.2.5 on 2026-09-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_salesdailyactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesactivityphoto',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Optional label/name for this photo (e.g. 'Ryan International Visit', 'Exhibition Day 1 — Stall Setup'). Useful for per-event photo identification.", max_length=200),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='reminder_two_days_before_sent',
            field=models.BooleanField(default=False, help_text='True once the 8:00 AM 2-days-before reminder has been sent.'),
        ),
    ]
