# Generated by Django 5.2.5 on 2026-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_event_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesactivityphoto',
            name='photo_type',
            field=models.CharField(help_text="Type/category of the photo (e.g. 'start_selfie', 'venue', 'meeting')", max_length=50),
        ),
    ]
