# Generated by Django 6.0.5 on 2026-09-15 05:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_remove_photo_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometerreading',
            name='expense_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Reimbursement rate per kilometer (auto-set based on vehicle_type: ₹2 for 2-wheeler, ₹12 for 4-wheeler)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='odometerreading',
            name='vehicle_type',
            field=models.CharField(choices=[('2_wheeler', '2 Wheeler'), ('4_wheeler', '4 Wheeler')], default='2_wheeler', help_text='Type of vehicle used: 2 wheeler (₹2/km) or 4 wheeler (₹12/km)', max_length=20),
        ),
    ]
