# Generated by Django 6.0.5 on 2026-09-15 06:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_odometerreading_expense_per_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odometerreading',
            name='expense_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Reimbursement rate per kilometer (auto-set based on vehicle_type: ₹5 for bike, ₹12 for car)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='odometerreading',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], default='bike', help_text='Type of vehicle used: bike (₹5/km) or car (₹12/km)', max_length=20),
        ),
    ]
