# Generated by Django 6.0.5 on 2026-09-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_odometerreading_expense_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='students_attended',
            field=models.PositiveIntegerField(blank=True, help_text='Number of students actually attended', null=True),
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='students_expected',
            field=models.PositiveIntegerField(blank=True, help_text='Number of students expected to attend', null=True),
        ),
    ]
