# Generated by Django 6.0.5 on 2026-09-18 09:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_salesdailyactivity_board_salesdailyactivity_medium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlanReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_time', models.DateTimeField(help_text='The exact time to send this reminder.')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether this reminder has been sent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(help_text='The sales plan this reminder is for.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_reminders', to='leads.salesdailyplan')),
            ],
            options={
                'db_table': 'sales_plan_reminders',
                'ordering': ['reminder_time'],
            },
        ),
    ]
