# Generated by Django 6.0.5 on 2026-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_salesplanreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='target_name',
            field=models.CharField(blank=True, help_text='Name of the person being targeted/visited', max_length=100),
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='target_number',
            field=models.CharField(blank=True, help_text='WhatsApp number of the target', max_length=20),
        ),
    ]
