# Generated by Django 6.0.5 on 2026-09-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_salesdailyactivity_target_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesplanreminder',
            name='purpose',
            field=models.CharField(blank=True, help_text='What this reminder is for (e.g. call, follow-up meeting, etc.)', max_length=255),
        ),
    ]
