# Generated by Django 6.0.5 on 2026-09-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_salesplanreminder_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', help_text='Current status of the activity', max_length=20),
        ),
    ]
