# Generated by Django 6.0.5 on 2026-09-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_salesdailyactivity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='location_link',
            field=models.URLField(blank=True, help_text='Google Map link for location/venue', null=True),
        ),
    ]
