# Generated by Django 6.0.5 on 2026-09-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_salesdailyactivity_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='from_date',
            field=models.DateField(blank=True, help_text='Start date of the activity', null=True),
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='to_date',
            field=models.DateField(blank=True, help_text='End date of the activity', null=True),
        ),
    ]
