# Generated by Django 6.0.5 on 2026-09-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_salesdailyactivity_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdailyactivity',
            name='board',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('gseb', 'GSEB'), ('cbic_ib', 'CBIC/IB')], default='cbse', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdailyactivity',
            name='medium',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi')], default='english', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdailyactivity',
            name='standard',
            field=models.CharField(blank=True, choices=[('12th', '12th'), ('11th_12th', '11th & 12th'), ('11th', '11th'), ('10th', '10th')], default='12th', max_length=20, null=True),
        ),
    ]
