# Generated by Django 6.0.5 on 2026-09-28 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_salesdailyactivity_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDailyActivityTiming',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The specific date for this timing')),
                ('start_time', models.TimeField(help_text='Start time for this day')),
                ('end_time', models.TimeField(help_text='End time for this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='leads.salesdailyactivity')),
            ],
            options={
                'db_table': 'sales_activity_timings',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
