# Generated by Django 6.0.5 on 2026-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_salesdailyactivitytiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdailyactivity',
            name='medium',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('gujarati_english', 'Gujarati+English')], default='english', max_length=20, null=True),
        ),
    ]
