# Generated by Django 6.0.5 on 2026-10-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemallocation_sales_user'),
        ('leads', '0028_salesdailyplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdailyplan',
            name='status',
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='inventory_allocations',
            field=models.ManyToManyField(blank=True, related_name='sales_plans', to='inventory.itemallocation'),
        ),
    ]
