# Generated by Django 6.0.5 on 2026-10-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_remove_salesdailyplan_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyplan',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Status of the plan', max_length=20),
        ),
    ]
