# Generated by Django 6.0.5 on 2026-10-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemallocation_sales_user'),
        ('leads', '0030_salesdailyplan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdailyplan',
            name='inventory_allocations',
        ),
        migrations.AddField(
            model_name='salesdailyactivity',
            name='inventory_allocations',
            field=models.ManyToManyField(blank=True, related_name='sales_activities', to='inventory.itemallocation'),
        ),
    ]
