# Generated by Django 6.0.5 on 2026-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_remove_salesdailyplan_inventory_allocations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdailyactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the activity', max_length=20),
        ),
    ]
