# Generated by Django 5.2.5 on 2026-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_alter_lead_group_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='violations_checked',
            field=models.BooleanField(default=False, help_text='True if the background task has already checked this activity for violations.'),
        ),
    ]
