# Generated by Django 5.2.5 on 2026-10-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_salesdailyactivity_violations_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdailyactivity',
            name='violations_checked',
        ),
    ]
