# Generated by Django 5.2.5 on 2026-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_remove_salesdailyactivity_violations_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdailyactivity',
            name='self_vehicle',
            field=models.BooleanField(default=False, help_text='Whether the user is using their own vehicle'),
        ),
        migrations.AddField(
            model_name='salesdailyplan',
            name='self_vehicle',
            field=models.BooleanField(default=False, help_text='Whether the user is using their own vehicle'),
        ),
    ]
