# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
import django.utils.timezone
import students.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('branch', '0001_initial'),
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('current_batch_name', models.CharField(blank=True, help_text='Batch name — will link to Batch.', max_length=200)),
                ('roll_number', models.CharField(blank=True, db_index=True, help_text='Roll number within batch.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Active student flag.')),
                ('qr_blocked', models.BooleanField(default=False, help_text='QR temporarily blocked due to violations.')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('phone_student', models.CharField(max_length=15)),
                ('phone_student_2', models.CharField(blank=True, max_length=15)),
                ('phone_father', models.CharField(max_length=15)),
                ('phone_father_2', models.CharField(blank=True, max_length=15)),
                ('street', models.TextField()),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('group_module', models.CharField(max_length=20)),
                ('batch_attempt', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo — mandatory for digital ID card generation.', null=True, upload_to=students.models.student_photo_path)),
                ('doc_signature', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_dob_certificate', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_id_proof', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_tenth_marksheet', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_twelfth_marksheet', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_category_cert', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('doc_graduation_cert', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('alumni', 'Alumni'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=15)),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes.')),
                ('admission', models.OneToOneField(help_text='The admission record this student was created from.', on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='onboarding.admission')),
                ('assigned_counsellor', models.ForeignKey(blank=True, limit_choices_to={'role': 'counsellor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselled_students', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, help_text='Current batch assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='batches.batch')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='branch.branch')),
                ('user', models.ForeignKey(help_text='Login account for this student.', on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], default='father', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact parent.')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parents'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'db_table': 'student_parent_links',
                'ordering': ['-is_primary', 'linked_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('uniform_shirt', 'Uniform Shirt'), ('uniform_trouser', 'Uniform Trouser'), ('uniform_blazer', 'Uniform Blazer'), ('book', 'Book'), ('id_card', 'ID Card'), ('other', 'Other')], max_length=30)),
                ('item_name', models.CharField(blank=True, help_text='e.g. Book title, ISBN, uniform size', max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('size', models.CharField(blank=True, help_text='For uniform items.', max_length=20)),
                ('isbn', models.CharField(blank=True, help_text='For books.', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_inventory', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_issues', to='students.student')),
            ],
            options={
                'db_table': 'student_inventory_issues',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalIDCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_data', models.CharField(help_text='Data encoded in QR (student UUID).', max_length=500)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=students.models.id_card_path)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to=students.models.id_card_path)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_card', to='students.student')),
            ],
            options={
                'db_table': 'student_digital_id_cards',
            },
        ),
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_history', to='students.student')),
            ],
            options={
                'db_table': 'student_batch_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('alumni', 'Alumni'), ('suspended', 'Suspended')], max_length=15)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('alumni', 'Alumni'), ('suspended', 'Suspended')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student')),
            ],
            options={
                'db_table': 'student_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='students_course_eb8ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['enrolled_at'], name='students_enrolle_f217e2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='students_email_b942ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parentlink',
            unique_together={('student', 'parent')},
        ),
    ]
