# Generated by Django 6.0.5 on 2026-05-30 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(help_text='Login account for this student.', on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
