# Generated by Django 4.2.29 on 2026-08-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(db_index=True, editable=False, max_length=100, unique=True),
        ),
    ]
