# Generated by Django 6.0.5 on 2026-09-15 04:38

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc_pan_card',
            field=models.FileField(blank=True, null=True, upload_to=students.models.student_document_path),
        ),
    ]
