# Generated by Django 6.0.5 on 2026-06-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_alter_subject_options_remove_batch_session_end_time_and_more'),
        ('students', '0003_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('students.student',),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Current batch assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active student flag.'),
        ),
        migrations.AddField(
            model_name='student',
            name='qr_blocked',
            field=models.BooleanField(default=False, help_text='QR temporarily blocked due to violations.'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='Roll number within batch.', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_batch_name',
            field=models.CharField(blank=True, help_text='Batch name — will link to Batch.', max_length=200),
        ),
    ]
