# Generated by Django 6.0.5 on 2026-07-02 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_manager', 'Branch Manager'), ('admin_senior_executive', 'Admin Senior Executive'), ('admin_executive', 'Admin Executive'), ('front_desk', 'Front Desk'), ('counsellor', 'Counsellor'), ('sales_senior_executive', 'Sales Senior Executive'), ('sales_executive', 'Sales Executive'), ('tele_caller', 'Tele Caller'), ('exam_supervisor', 'Exam Supervisor'), ('paper_checker', 'Paper Checker'), ('accountant', 'Accountant'), ('student', 'Student'), ('parents', 'Parents'), ('faculty', 'Faculty'), ('house_keeping', 'House Keeping'), ('security', 'Security')], default='student', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('fcm_token', models.TextField(blank=True, default='', help_text='Firebase Cloud Messaging device token for push notifications.')),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/photos/')),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('subject_expertise', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('executive', 'Executive'), ('professional', 'Professional')], default='executive', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('visiting', 'Visiting')], default='full_time', max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('session_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/employee/')),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('salary_retention_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of gross salary to retain each month.', max_digits=5)),
                ('per_paper_rate', models.DecimalField(decimal_places=2, default=0, help_text='Per-paper rate for paper_checker role (new FRD). Payment = papers_checked * rate - late_submission_penalties (5 days grace after exam.scheduled_date; then +5% per 7-day bracket).', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('primary_color', models.CharField(blank=True, default='#2563EB', max_length=7)),
                ('website_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordSetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
