# Generated by Django 6.0.5 on 2026-05-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_manager', 'Branch Manager'), ('admin_senior_executive', 'Admin Senior Executive'), ('admin_executive', 'Admin Executive'), ('front_desk', 'Front Desk'), ('counsellor', 'Counsellor'), ('sales_senior_executive', 'Sales Senior Executive'), ('sales_executive', 'Sales Executive'), ('tele_caller', 'Tele Caller'), ('exam_supervisor', 'Exam Supervisor'), ('paper_checker', 'Paper Checker'), ('accountant', 'Accountant'), ('student', 'Student'), ('parents', 'Parents'), ('faculty', 'Faculty')], default='student', max_length=50),
        ),
    ]
