# Generated by Django 6.0.5 on 2026-07-06 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='linked_student',
        ),
        migrations.AddField(
            model_name='user',
            name='linked_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='linked_parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
