# Generated by Django 4.2.29 on 2026-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0003_remove_user_linked_student_user_linked_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_modules',
            field=models.JSONField(blank=True, help_text='List of modules this user has access to. If null, falls back to role default modules.', null=True),
        ),
    ]
