# Generated by Django 6.0.5 on 2026-07-16 11:44

from django.db import migrations


def update_existing_users(apps, schema_editor):
    User = apps.get_model('auth_user', 'User')
    roles_to_fix = [
        'accountant', 'sales_executive', 'front_desk', 
        'counsellor', 'paper_checker', 'sales_senior_executive', 'tele_caller'
    ]
    
    users = User.objects.filter(role__in=roles_to_fix)
    for user in users:
        if user.accessible_modules is not None:
            modules = list(user.accessible_modules)
            changed = False
            if 'attendance' not in modules:
                modules.append('attendance')
                changed = True
            if 'notifications' not in modules:
                modules.append('notifications')
                changed = True
            if changed:
                user.accessible_modules = modules
                user.save(update_fields=['accessible_modules'])

class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_user_aadhar_number'),
    ]

    operations = [
        migrations.RunPython(update_existing_users, reverse_code=migrations.RunPython.noop),
    ]
