# Generated by Django 4.2.29 on 2026-07-21 11:51

from django.db import migrations


def remove_attendance(apps, schema_editor):
    User = apps.get_model('auth_user', 'User')
    users = User.objects.filter(role='paper_checker')
    for user in users:
        if user.accessible_modules is not None:
            modules = list(user.accessible_modules)
            if 'attendance' in modules:
                modules.remove('attendance')
                user.accessible_modules = modules
                user.save(update_fields=['accessible_modules'])

class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_add_attendance_notifications_to_existing_roles'),
    ]

    operations = [
        migrations.RunPython(remove_attendance, reverse_code=migrations.RunPython.noop),
    ]
