# Generated by Django 6.0.5 on 2026-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_remove_attendance_from_paper_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting')], default='full_time', max_length=20),
        ),
    ]
