# Generated by Django 6.0.5 on 2026-06-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, default='', help_text='Firebase Cloud Messaging device token for push notifications.'),
        ),
    ]
