# Generated by Django 6.0.5 on 2026-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_user_employment_type'),
        ('branch', '0002_branch_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text="Additional branches this user can access. The primary branch is set via the 'branch' FK above.", related_name='multi_branch_users', to='branch.branch'),
        ),
    ]
