# Generated by Django 6.0.5 on 2026-08-03 05:26

from django.db import migrations


def backfill_branch_to_branches(apps, schema_editor):
    """
    For every existing User that has a primary branch FK set but does NOT yet
    have that branch in their branches M2M, add it.
    This ensures old users are fully migrated to the new multi-branch model
    without losing their existing branch assignment.
    """
    User = apps.get_model('auth_user', 'User')
    updated = 0
    for user in User.objects.filter(branch__isnull=False):
        # Only add if not already present (idempotent)
        if not user.branches.filter(id=user.branch_id).exists():
            user.branches.add(user.branch)
            updated += 1
    print(f"\n  [backfill] Migrated {updated} user(s): branch FK -> branches M2M.")


def reverse_backfill(apps, schema_editor):
    # No-op: removing items from M2M won't affect old FK values, safe to skip.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_user_branches'),
    ]

    operations = [
        migrations.RunPython(backfill_branch_to_branches, reverse_backfill),
    ]
