# Generated by Django

from django.db import migrations


def update_existing_users(apps, schema_editor):
    User = apps.get_model('auth_user', 'User')
    roles_to_fix = [
        'front_desk', 'tele_caller', 'counsellor', 
        'sales_senior_executive', 'accountant'
    ]
    
    users = User.objects.filter(role__in=roles_to_fix)
    for user in users:
        if user.accessible_modules is not None:
            modules = list(user.accessible_modules)
            changed = False
            if 'leave' not in modules:
                modules.append('leave')
                changed = True
            if changed:
                user.accessible_modules = modules
                user.save(update_fields=['accessible_modules'])

class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_backfill_branch_fk_into_branches_m2m'),
    ]

    operations = [
        migrations.RunPython(update_existing_users, reverse_code=migrations.RunPython.noop),
    ]
