# Generated by Django 5.2.8 on 2026-06-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of gross salary to retain each month.', max_digits=5),
        ),
    ]
