# Generated by Django 6.0.5 on 2026-09-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0012_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('authentication', 'Authentication'), ('admission', 'Admission'), ('attendance', 'Attendance'), ('timetable', 'Timetable'), ('chat', 'Chat'), ('exam', 'Exam'), ('fees', 'Fees'), ('inventory', 'Inventory'), ('leads', 'Leads'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('results', 'Results'), ('support', 'Support')], default='system', max_length=50),
        ),
    ]
