# Generated by Django 6.0.5 on 2026-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0013_notificationhistory_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_manager', 'Branch Manager'), ('admin_senior_executive', 'Admin Senior Executive'), ('admin_executive', 'Admin Executive'), ('front_desk', 'Front Desk'), ('counsellor', 'Counsellor'), ('sales_senior_executive', 'Sales Senior Executive'), ('sales_executive', 'Sales Executive'), ('tele_caller', 'Tele Caller'), ('head_coordinator', 'Head Coordinator'), ('senior_tele_caller', 'Senior Tele Caller'), ('cmo', 'CMO'), ('associate_bdm', 'Associate Business Development Manager'), ('printers', 'Printers'), ('exam_supervisor', 'Exam Supervisor'), ('paper_checker', 'Paper Checker'), ('accountant', 'Accountant'), ('student', 'Student'), ('parents', 'Parents'), ('faculty', 'Faculty'), ('house_keeping', 'House Keeping'), ('security', 'Security')], default='student', max_length=50),
        ),
    ]
