# Generated by Django 6.0.5 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0014_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list, help_text='List of additional roles for this user. Modules from these roles are merged into accessible_modules.', null=True),
        ),
    ]
