# Generated by Django 6.0.5 on 2026-06-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0014_user_bank_account_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='per_paper_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Per-paper rate for paper_checker role (new FRD). Payment = papers_checked * rate - late_submission_penalties (5 days grace after exam.scheduled_date; then +5% per 7-day bracket).', max_digits=8),
        ),
    ]
