# Generated by Django 5.1.1 on 2026-09-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0015_user_additional_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('authentication', 'Authentication'), ('admission', 'Admission'), ('attendance', 'Attendance'), ('timetable', 'Timetable'), ('chat', 'Chat'), ('exam', 'Exam'), ('fees', 'Fees'), ('inventory', 'Inventory'), ('leads', 'Leads'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('results', 'Results'), ('sales', 'Sales'), ('support', 'Support')], default='system', max_length=50),
        ),
    ]
