# Generated by Django

from django.db import migrations


def add_inventory_to_sales_roles(apps, schema_editor):
    User = apps.get_model('auth_user', 'User')
    sales_roles = [
        'sales_senior_executive',
        'sales_executive',
        'tele_caller',
        'senior_tele_caller',
        'associate_bdm',
    ]

    users = User.objects.filter(role__in=sales_roles)
    for user in users:
        if user.accessible_modules is not None:
            modules = list(user.accessible_modules)
            if 'inventory' not in modules:
                modules.append('inventory')
                user.accessible_modules = modules
                user.save(update_fields=['accessible_modules'])


def reverse_inventory_from_sales_roles(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0016_alter_notificationhistory_notification_type'),
    ]

    operations = [
        migrations.RunPython(add_inventory_to_sales_roles, reverse_code=reverse_inventory_from_sales_roles),
    ]
