# Generated by Django

from django.db import migrations


def add_inventory_to_student_parent_faculty(apps, schema_editor):
    User = apps.get_model('auth_user', 'User')
    target_roles = [
        'student',
        'parents',
        'faculty',
    ]

    users = User.objects.filter(role__in=target_roles)
    for user in users:
        if user.accessible_modules is not None:
            modules = list(user.accessible_modules)
            if 'inventory' not in modules:
                modules.append('inventory')
                user.accessible_modules = modules
                user.save(update_fields=['accessible_modules'])


def reverse_inventory(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0017_add_inventory_to_sales_roles'),
    ]

    operations = [
        migrations.RunPython(add_inventory_to_student_parent_faculty, reverse_code=reverse_inventory),
    ]
