# Generated by Django 6.0.5 on 2026-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0018_add_inventory_to_student_parent_faculty'),
        ('batches', '0009_auto_chat_room_for_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='faculty_users', to='batches.courselevel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('executive', 'Executive'), ('professional', 'Professional')], default='executive', max_length=50),
        ),
    ]
