# Generated by Django 6.0.5 on 2026-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0020_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total working hours', max_digits=5),
        ),
    ]
