# Generated by Django 6.0.5 on 2026-05-28 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_subject'),
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('subject_expertise', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('executive', 'Executive'), ('professional', 'Professional')], default='executive', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('joining_date', models.DateField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('pan_number', models.CharField(blank=True, max_length=15)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/faculty/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profiles', to='branches.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'faculty_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyQRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scan_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], default='check_in', max_length=10)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='faculty.facultyprofile')),
            ],
            options={
                'db_table': 'faculty_qr_scans',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('chapter_covered', models.CharField(max_length=300)),
                ('topics_covered', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='completed', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='batches.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='faculty.facultyprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='batches.subject')),
            ],
            options={
                'db_table': 'faculty_session_reports',
                'ordering': ['-session_date', '-start_time'],
            },
        ),
    ]
