# Generated by Django 6.0.5 on 2026-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultyprofile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
