# Generated by Django 6.0.5 on 2026-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0010_chapter_faculties'),
        ('faculty', '0002_alter_facultyprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='faculty_profiles', to='batches.courselevel'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('executive', 'Executive'), ('professional', 'Professional')], default='executive', max_length=50),
        ),
    ]
