# Generated by Django 6.0.5 on 2026-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0021_alter_timetableslot_slot_code'),
        ('faculty', '0003_alter_facultyprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyqrscanlog',
            name='early_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyqrscanlog',
            name='is_early_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='session_reports', to='batches.chapter'),
        ),
    ]
