# Generated by Django 6.0.5 on 2026-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_facultyqrscanlog_early_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='session_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
