# Generated by Django 6.0.5 on 2026-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_facultyprofile_session_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('visiting', 'Visiting')], default='full_time', max_length=20),
        ),
    ]
