# Generated by Django 6.0.5 on 2026-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_facultyprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='work_end_time',
            field=models.TimeField(blank=True, help_text='Faculty shift end time (e.g. 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='work_start_time',
            field=models.TimeField(blank=True, help_text='Faculty shift start time (e.g. 09:00)', null=True),
        ),
    ]
