# Generated by Django 5.2.8 on 2026-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_facultyprofile_work_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='salary_retention_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
