# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.studentfee'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='fees.studentfee'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['course', 'is_active'], name='fee_structu_course__36f3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['batch', 'is_active'], name='fee_structu_batch_i_748ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentitem',
            index=models.Index(fields=['plan', 'is_paid'], name='installment_plan_id_54e010_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentitem',
            index=models.Index(fields=['due_date', 'is_paid'], name='installment_due_dat_b92dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refunds_payment_908281_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['-created_at'], name='refunds_created_22de57_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'status'], name='student_fee_student_40a6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status', 'due_date'], name='student_fee_status_e37e73_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['-created_at'], name='student_fee_created_8906e4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status'], name='payments_student_2f940c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['receipt_number'], name='payments_receipt_6cb761_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='payments_status_811742_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student_fee', 'status'], name='payments_student_7e400b_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['student_fee', 'status'], name='installment_student_9e1640_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['-created_at'], name='installment_created_982e6b_idx'),
        ),
    ]
