# Generated by Django 6.0.5 on 2026-07-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated as sum of components below', max_digits=10),
        ),
    ]
