# Generated by Django 5.2.8 on 2026-05-28 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_batches_course__ab81b0_idx_and_more'),
        ('fees', '0002_alter_bankaccount_id_alter_feestructure_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='bank_accoun_is_acti_1a9d00_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['course', 'is_active'], name='fee_structu_course__36f3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['batch', 'is_active'], name='fee_structu_batch_i_748ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentitem',
            index=models.Index(fields=['plan', 'is_paid'], name='installment_plan_id_54e010_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentitem',
            index=models.Index(fields=['due_date', 'is_paid'], name='installment_due_dat_b92dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['student_fee', 'status'], name='installment_student_9e1640_idx'),
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['-created_at'], name='installment_created_982e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='payments_status_811742_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student_fee', 'status'], name='payments_student_7e400b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'status'], name='refunds_payment_908281_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['-created_at'], name='refunds_created_22de57_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status', 'due_date'], name='student_fee_status_e37e73_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['-created_at'], name='student_fee_created_8906e4_idx'),
        ),
    ]
