# Generated by Django 5.2.8 on 2026-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feestructure_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='m_id',
            field=models.CharField(blank=True, help_text='UPI ID for generating UPI payment links', max_length=100, null=True),
        ),
    ]
