# Generated by Django 4.2.29 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_bankaccount_bank_accoun_is_acti_1a9d00_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Approval Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Approval Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Approval Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
