# Generated by Django 4.2.29 on 2026-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_payment_status_alter_refund_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('approval_pending', 'Approval Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='approval_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('approval_pending', 'Approval Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='approval_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('approval_pending', 'Approval Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='approval_pending', max_length=20),
        ),
    ]
