# Generated by Django 5.1.1 on 2026-08-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_bankaccount_m_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='razorpay_account_id',
            field=models.CharField(blank=True, help_text='Razorpay Linked Account ID (e.g. acc_...) for Route transfers', max_length=100, null=True),
        ),
    ]
