# Generated by Django 6.0.5 on 2026-06-09 04:49

import django.db.models.deletion
from django.db import migrations, models


def migrate_user_to_student_fk(apps, schema_editor):
    """
    The student_id column currently stores User UUIDs.
    We need to replace them with the corresponding Student UUIDs.
    Student.user is a FK to User, so we can look up the Student by user_id.
    """
    Student = apps.get_model('students', 'Student')
    StudentFee = apps.get_model('fees', 'StudentFee')
    Payment = apps.get_model('fees', 'Payment')

    # Build a lookup: user_id -> student_id
    user_to_student = {}
    for s in Student.objects.all():
        user_to_student[s.user_id] = s.id

    # Helper function to get student, or delete the record if missing
    # Update StudentFee
    for sf in StudentFee.objects.all():
        student_id = user_to_student.get(sf.student_id)
        if student_id:
            if student_id != sf.student_id:
                sf.student_id = student_id
                sf.save(update_fields=['student_id'])
        else:
            sf.delete()

    # Update Payment
    for p in Payment.objects.all():
        student_id = user_to_student.get(p.student_id)
        if student_id:
            if student_id != p.student_id:
                p.student_id = student_id
                p.save(update_fields=['student_id'])
        else:
            p.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_payment_status_alter_refund_status_and_more'),
        ('students', '0004_studentprofile_student_batch_student_is_active_and_more'),
    ]

    operations = [
        # Step 1: Migrate existing User UUIDs to Student UUIDs
        migrations.RunPython(
            migrate_user_to_student_fk,
            migrations.RunPython.noop,
        ),
        # Step 2: Alter field targets
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student'),
        ),
    ]
