# Generated by Django 6.0.5 on 2026-09-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_bankaccount_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='icsi_registration_fees_direct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICSI Registration Fees Direct'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='icsi_registration_fees_via_cseet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICSI Registration Fees via CSEET'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_both_modules',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Both Modules'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_module_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Module 1'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_module_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Module 2'),
        ),
    ]
