# Generated by Django 6.0.5 on 2026-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feestructure_icsi_registration_fees_direct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='attempt',
            field=models.CharField(blank=True, choices=[('june', 'June'), ('oct', 'October'), ('feb', 'February'), ('dec', 'December')], max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
