# Generated by Django 6.0.5 on 2026-06-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_fk_consistency_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_document',
            field=models.FileField(blank=True, null=True, upload_to='payments/documents/'),
        ),
    ]
