# Generated by Django 6.0.5 on 2026-06-18 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0018_batch_qr_image'),
        ('fees', '0007_payment_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='batches.courselevel'),
        ),
    ]
