# Generated by Django 5.2.5 on 2026-10-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_feestructure_attempt_feestructure_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='group_module',
            field=models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module')], max_length=20),
        ),
    ]
