# Generated by Django 6.0.5 on 2026-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_feestructure_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='max_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
