# Generated by Django 5.2.5 on 2026-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_feestructure_group_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='institute_fees_both_modules',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_all_modules',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for All Modules'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_module_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Module 3'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_module_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Module 4'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='institute_fees_module_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Institute Fees for Module 5'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='group_module',
            field=models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('all', 'All Modules'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module'), ('module_4', '4th Module'), ('module_5', '5th Module')], max_length=20),
        ),
    ]
