# Generated by Django 6.0.5 on 2026-06-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_bankaccount_max_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='icsi_exam_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICSI Exam Fees'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='icsi_registration_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ICSI Registration Fees'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='token_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Token Amount'),
        ),
    ]
