# Generated by Django 5.2.8 on 2026-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='event',
            field=models.CharField(blank=True, default='', help_text='Human readable event based on API', max_length=255),
        ),
    ]
