# Generated by Django 6.0.5 on 2026-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Set when the recipient first connects after this message was sent.', null=True),
        ),
    ]
