# Generated by Django 5.2.5 on 2026-06-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. Content replaced by placeholder when True.'),
        ),
    ]
