# Generated by Django 5.2.8 on 2026-07-22 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wa_message_id', models.CharField(db_index=True, help_text="Meta's wamid (WhatsApp message ID).", max_length=255, unique=True)),
                ('sender_wa_id', models.CharField(help_text="Sender's WhatsApp ID (phone number without +).", max_length=20)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_type', models.CharField(default='text', help_text='text, image, document, video, audio, location, interactive, button, reaction', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Media IDs, reply metadata, etc.')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Matched system user (if phone is recognized).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
