# Generated by Django 6.0.5 on 2026-06-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='direct_hash',
            field=models.CharField(blank=True, default='', help_text="For direct rooms only: sorted user-UUID pair separated by '_' to guarantee uniqueness.", max_length=100),
        ),
    ]
