# Generated by Django 6.0.5 on 2026-06-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_is_deleted_to_message'),
        ('chat', '0004_alter_chatroom_direct_hash'),
    ]

    operations = [
    ]
