# Generated by Django 6.0.5 on 2026-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20260605_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
    ]
