# Generated by Django 6.0.5 on 2026-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Group avatar URL (for group rooms).', max_length=1024, null=True),
        ),
    ]
