# Generated by Django 6.0.5 on 2026-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatroom_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Group avatar image.', null=True, upload_to='chat/group_avatars/'),
        ),
    ]
