# Generated by Django 6.0.5 on 2026-06-25 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatroom_avatar_url_chatroom_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target',
            field=models.ForeignKey(blank=True, help_text='If set in a group room, this message is visible ONLY to: sender, the target (e.g. specific faculty), and super_admin. Normal group messages have target=None.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
