# Generated by Django 6.0.5 on 2026-06-25 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_add_target_to_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='target',
        ),
        migrations.AddField(
            model_name='message',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='If set in a group room, this message is visible ONLY to: sender, any of the listed targets (e.g. specific faculty members), and super_admin. Normal group messages have no targets.', related_name='targeted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
