from .dashboard import get_dashboard_data
from .students import get_student_report
from .attendance import get_attendance_report
from .fees import get_fee_report
from .timetable import get_timetable_report
from .exams import get_exam_report
from .payroll import get_payroll_report
from .leads import get_lead_report
from .leaves import get_leave_report
