# Generated by Django 5.2.8 on 2026-07-29 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_alter_user_employment_type'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_queries', to='auth_user.organization'),
        ),
    ]
