# Generated by Django 5.2.8 on 2026-07-29 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportquery_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportquery',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member assigned to handle this query.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportquery',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('reopened', 'Reopened')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportQueryMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('is_resolution', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportquery')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
