# Generated by Django 6.0.5 on 2026-05-27 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exam_checker_tokens',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exam_choices',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=20)),
                ('total_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('duration_minutes', models.IntegerField(help_text='Drives the countdown timer')),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('results_published', 'Results Published')], default='draft', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('geo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_radius_meters', models.IntegerField(default=0, help_text='0 = geo check disabled')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=200)),
                ('student_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('student_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('screen_lock_violations', models.IntegerField(default=0)),
                ('split_screen_warnings', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'exam_sessions',
            },
        ),
        migrations.CreateModel(
            name='MalpracticeReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('disqualified', 'Disqualified')], max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'exam_malpractice',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'MCQ'), ('subjective', 'Subjective'), ('true_false', 'True/False')], max_length=20)),
                ('marks', models.IntegerField()),
                ('order', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_questions/')),
            ],
            options={
                'db_table': 'exam_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScreenEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('lock_breach', 'Lock Breach'), ('split_screen', 'Split Screen')], max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.CharField(choices=[('logged', 'Logged'), ('warning_issued', 'Warning Issued'), ('auto_submitted', 'Auto Submitted')], default='logged', max_length=20)),
            ],
            options={
                'db_table': 'exam_screen_events',
            },
        ),
        migrations.CreateModel(
            name='SeatArrangement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(max_length=20)),
                ('row_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_seating',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exam_student_answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerKeyDistributionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('link_expires', models.DateTimeField()),
                ('sent_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_answer_key_logs',
            },
        ),
    ]
