# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('branch', '0001_initial'),
        ('exams', '0001_initial'),
        ('faculty', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checkertoken',
            name='marksheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='results.marksheet'),
        ),
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='paper_checkers',
            field=models.ManyToManyField(blank=True, help_text="Available paper checkers assignable to this exam's marksheets. Auto-assignment uses these + time slot availability.", limit_choices_to={'is_active': True, 'role': 'paper_checker'}, related_name='exams_to_check', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='batches.subject'),
        ),
        migrations.AddField(
            model_name='answerkeydistributionlog',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key_logs', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam'),
        ),
    ]
