# Generated by Django 6.0.5 on 2026-05-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='geo_check_interval_minutes',
            field=models.IntegerField(default=0, help_text='0 = check only at start. >0 = also check periodically during exam at this interval.'),
        ),
        migrations.AddField(
            model_name='exam',
            name='result_release_mode',
            field=models.CharField(choices=[('instant', 'Instant'), ('manual', 'Manual')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='screen_lock_action',
            field=models.CharField(choices=[('flag_only', 'Flag Only'), ('auto_submit', 'Auto Submit')], default='auto_submit', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='screen_lock_max_violations',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exam',
            name='split_screen_action',
            field=models.CharField(choices=[('flag_only', 'Flag Only'), ('auto_submit', 'Auto Submit')], default='auto_submit', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='split_screen_max_warnings',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='examsession',
            name='last_geo_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screenevent',
            name='action_taken',
            field=models.CharField(choices=[('logged', 'Logged'), ('warning_issued', 'Warning Issued'), ('auto_submitted', 'Auto Submitted'), ('flagged', 'Flagged')], default='logged', max_length=20),
        ),
    ]
