# Generated by Django 6.0.5 on 2026-07-02 05:00

from django.db import migrations, models


def migrate_exam_types(apps, schema_editor):
    """Data migration for splitting overloaded exam_type into exam_mode + exam_type.
    Old values 'online'/'offline' moved to new exam_mode field (default online).
    Legacy exams using mode as type get exam_type='mcq' (common case).
    Keeps backward compatibility for existing DB records.
    """
    Exam = apps.get_model('exams', 'Exam')
    for exam in Exam.objects.all():
        if getattr(exam, 'exam_type', None) in ('online', 'offline'):
            exam.exam_mode = exam.exam_type
            exam.exam_type = 'mcq'  # default for previously mode-only exams
        else:
            exam.exam_mode = 'online'
        exam.save(update_fields=['exam_mode', 'exam_type'])


def reverse_migrate_exam_types(apps, schema_editor):
    """No-op reverse (data split is not easily reversible without losing info)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_mode',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('online', 'Online'),
                    ('offline', 'Offline'),
                ],
                default='online',
                help_text='Mode of exam (online = digital proctored, offline = paper-based with uploaded question papers)'
            ),
        ),
        migrations.RunPython(migrate_exam_types, reverse_migrate_exam_types),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('subjective', 'Subjective')], max_length=20),
        ),
    ]
