# Generated by Django 5.2.5 on 2026-06-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_geo_check_interval_minutes_and_more'),
        ('faculty', '0003_alter_facultyprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to='faculty.facultyprofile'),
        ),
    ]
