# Generated by Django 6.0.5 on 2026-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='answer_key',
            field=models.FileField(blank=True, help_text='Uploaded answer key (PDF/image). Must be present before allowing recheck requests or bulk recheck.', null=True, upload_to='answer_keys/'),
        ),
    ]
