# Generated by Django 6.0.5 on 2026-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_add_exam_mode_and_refactor_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='uploaded_answer_sheet',
            field=models.FileField(blank=True, help_text='Scanned or PDF answer sheet uploaded by student for subjective exams.', null=True, upload_to='student_answers/'),
        ),
    ]
