# Generated by Django 6.0.5 on 2026-07-07 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examsession_uploaded_answer_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='supervisors',
            field=models.ManyToManyField(blank=True, help_text='Exam supervisors assigned to invigilate this exam.', limit_choices_to={'is_active': True, 'role': 'exam_supervisor'}, related_name='supervised_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
