# Generated by Django 6.0.5 on 2026-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_add_answer_key_to_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=0, help_text='Auto-calculated as sum of all questions.marks (questions including MCQs can have varying marks per question). Updated automatically via signals.'),
        ),
    ]
