# Generated by Django 6.0.5 on 2026-06-25 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_total_marks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='paper_checkers',
            field=models.ManyToManyField(blank=True, help_text="Available paper checkers assignable to this exam's marksheets. Auto-assignment uses these + time slot availability.", limit_choices_to={'is_active': True, 'role': 'paper_checker'}, related_name='exams_to_check', to=settings.AUTH_USER_MODEL),
        ),
    ]
