# Generated by Django 6.0.5 on 2026-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_supervisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectpaper',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
