# Generated by Django 5.2.8 on 2026-06-27 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_paper_checkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_name', models.CharField(help_text='e.g., Set A, Morning Shift', max_length=50)),
                ('file', models.FileField(upload_to='exam_papers/')),
                ('answer_key', models.FileField(blank=True, null=True, upload_to='exam_papers/answer_keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exams.exam')),
            ],
            options={
                'db_table': 'exam_papers',
                'unique_together': {('exam', 'set_name')},
            },
        ),
        migrations.AddField(
            model_name='examsession',
            name='assigned_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exams.exampaper'),
        ),
    ]
