# Generated by Django 6.0.5 on 2026-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_subjectpaper_no_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='reminder_1d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
