# Generated by Django 6.0.5 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_reminder_1d_sent_exam_reminder_1h_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grace_marks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Grace marks added to the total of all students for this exam.', max_digits=5),
        ),
        migrations.AddField(
            model_name='exam',
            name='grace_marks_note',
            field=models.TextField(blank=True, help_text='Reason/note for providing grace marks (will be appended to marksheet remarks).'),
        ),
    ]
