# Generated by Django 5.2.8 on 2026-06-29 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0021_alter_timetableslot_slot_code'),
        ('exams', '0008_exampaper_examsession_assigned_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_name', models.CharField(help_text='e.g., Set A, Morning Shift', max_length=50)),
                ('file', models.FileField(upload_to='subject_papers/')),
                ('answer_key', models.FileField(blank=True, null=True, upload_to='subject_papers/answer_keys/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='batches.subject')),
            ],
            options={
                'db_table': 'subject_papers',
                'unique_together': {('subject', 'set_name')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='selected_papers',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to='exams.subjectpaper'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='assigned_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exams.subjectpaper'),
        ),
        migrations.DeleteModel(
            name='ExamPaper',
        ),
    ]
