# Generated by Django 6.0.5 on 2026-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_grace_marks_exam_grace_marks_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectpaper',
            name='set_name',
            field=models.CharField(blank=True, default='', help_text='e.g., Set A, Morning Shift. Auto-derived from filename if left blank.', max_length=500),
        ),
    ]
