# Generated by Django 5.2.8 on 2026-06-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_subjectpaper_exam_selected_papers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectpaper',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectpaper',
            name='set_name',
            field=models.CharField(blank=True, default='', help_text='e.g., Set A, Morning Shift. Auto-derived from filename if left blank.', max_length=50),
        ),
    ]
