# Generated by Django 6.0.5 on 2026-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_subjectpaper_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paragraph_text',
            field=models.TextField(blank=True, default='', help_text='For paragraph_mcq type: the comprehension passage that sub-questions refer to.'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mcq', 'MCQ'), ('subjective', 'Subjective')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('paragraph_mcq', 'Paragraph MCQ'), ('subjective', 'Subjective'), ('true_false', 'True/False')], max_length=20),
        ),
    ]
