# Generated by Django 4.2.29 on 2026-06-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0021_alter_timetableslot_slot_code'),
        ('exams', '0011_add_paragraph_mcq_and_exam_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='batches.subject'),
        ),
    ]
