# Generated by Django 6.0.5 on 2026-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., S, M, L, XL (useful for uniforms)', max_length=50),
        ),
        migrations.AddField(
            model_name='itemallocation',
            name='size',
            field=models.CharField(blank=True, help_text='Specific size allocated (e.g., M, L, XL)', max_length=20),
        ),
    ]
