# Generated by Django 6.0.5 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_size_itemallocation_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemallocation',
            name='size',
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit / Unique Item Code (Auto-generated if blank)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost at the time of transaction', max_digits=10, null=True),
        ),
    ]
