# Generated by Django 6.0.5 on 2026-06-22 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_itemallocation_size_alter_item_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
    ]
