# Generated by Django 6.0.5 on 2026-06-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='invoice_document',
            field=models.FileField(blank=True, help_text='Attach invoice document for purchase transactions', null=True, upload_to='inventory/invoices/'),
        ),
    ]
