# Generated by Django 6.0.5 on 2026-05-27 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('session_start_time', models.TimeField(blank=True, help_text='Start time used by attendance delay tasks.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='branches.branch')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'db_table': 'batches',
            },
        ),
    ]
