# Generated by Django 5.2.8 on 2026-05-28 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
    ]
