# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='faculty.facultyprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='batchsequencecounter',
            unique_together={('course_type', 'batch_attempt', 'attempt_year')},
        ),
        migrations.AddField(
            model_name='batchstudent',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_students', to='batches.batch'),
        ),
    ]
