# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0002_initial'),
        ('batches', '0002_initial'),
        ('exams', '0003_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='batches.course'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='batches.course'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_levels', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='batches.courselevel'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='batches.subject'),
        ),
        migrations.AddField(
            model_name='batchfaculty',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_assignments', to='batches.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='batches.batch'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='timetable_slots', to='batches.chapter'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='batches.classroom'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetable_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slot', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='examiners',
            field=models.ManyToManyField(blank=True, related_name='examiner_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='paper_checkers',
            field=models.ManyToManyField(blank=True, related_name='checker_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='batches.subject'),
        ),
        migrations.AddIndex(
            model_name='batchstudent',
            index=models.Index(fields=['student'], name='batch_stude_student_f1ea65_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstudent',
            index=models.Index(fields=['-enrolled_at'], name='batch_stude_enrolle_36f9a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchstudent',
            unique_together={('batch', 'student')},
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='classrooms_is_acti_148ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='courses_created_c00611_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_code'], name='batches_batch_c_5ac928_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['is_active'], name='batches_is_acti_20ba4f_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course', 'is_active'], name='batches_course__ab81b0_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date', 'end_date'], name='batches_start_d_2692ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['level', 'is_active'], name='subjects_level_i_74a74f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-created_at'], name='subjects_created_5c9ba3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('level', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'order')},
        ),
        migrations.AddIndex(
            model_name='batchfaculty',
            index=models.Index(fields=['faculty'], name='batch_facul_faculty_6d2f84_idx'),
        ),
        migrations.AddIndex(
            model_name='batchfaculty',
            index=models.Index(fields=['-assigned_at'], name='batch_facul_assigne_d0588f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchfaculty',
            unique_together={('batch', 'faculty', 'subject')},
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['batch', 'day_of_week'], name='timetable_s_batch_i_18246d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['faculty', 'day_of_week'], name='timetable_s_faculty_9463df_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['classroom', 'day_of_week'], name='timetable_s_classro_d003e2_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['batch', '-created_at'], name='timetable_s_batch_i_c2c98f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['session_type'], name='timetable_s_session_88258c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['session_date'], name='timetable_s_session_b04285_idx'),
        ),
    ]
