# Generated by Django 5.2.8 on 2026-05-28 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_alter_batch_id_alter_batchfaculty_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course', 'is_active'], name='batches_course__ab81b0_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date', 'end_date'], name='batches_start_d_2692ff_idx'),
        ),
        migrations.AddIndex(
            model_name='batchfaculty',
            index=models.Index(fields=['faculty'], name='batch_facul_faculty_6d2f84_idx'),
        ),
        migrations.AddIndex(
            model_name='batchfaculty',
            index=models.Index(fields=['-assigned_at'], name='batch_facul_assigne_d0588f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstudent',
            index=models.Index(fields=['student'], name='batch_stude_student_f1ea65_idx'),
        ),
        migrations.AddIndex(
            model_name='batchstudent',
            index=models.Index(fields=['-enrolled_at'], name='batch_stude_enrolle_36f9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='classrooms_is_acti_148ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type', 'is_active'], name='courses_course__6e31c1_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='courses_created_c00611_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course', 'is_active'], name='subjects_course__668b86_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-created_at'], name='subjects_created_5c9ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['batch', '-created_at'], name='timetable_s_batch_i_c2c98f_idx'),
        ),
    ]
