# Generated by Django 6.0.5 on 2026-05-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='session_end_time',
            field=models.TimeField(blank=True, help_text='End time used by attendance checkout tasks.', null=True),
        ),
    ]
