# Generated by Django 6.0.5 on 2026-06-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0003_batch_batches_course__ab81b0_idx_and_more'),
    ]

    operations = [
    ]
