# Generated by Django 6.0.5 on 2026-06-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0004_merge_20260601_1251'),
    ]

    operations = [
    ]
