# Generated by Django 6.0.5 on 2026-07-04 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0005_populate_chapters_fix'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchsequencecounter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batchsequencecounter',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_counters', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='group_module',
            field=models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='batchsequencecounter',
            unique_together={('course_type', 'batch_attempt', 'attempt_year', 'branch')},
        ),
    ]
