# Generated by Django 5.2.14 on 2026-06-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_organization_user_organization'),
        ('batches', '0005_alter_subject_options_remove_batch_session_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='auth_user.organization'),
        ),
    ]
