# Generated by Django 6.0.5 on 2026-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_batch_organization_classroom_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
