# Generated by Django 4.2.29 on 2026-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_force_populate_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='max_students',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
