# Generated by Django 6.0.5 on 2026-06-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0007_alter_batch_batch_code_alter_course_code_and_more'),
        ('students', '0004_studentprofile_student_batch_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='students.student'),
        ),
    ]
