# Generated by Django 6.0.5 on 2026-06-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_alter_batchstudent_student'),
        ('faculty', '0003_alter_facultyprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='faculty.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='faculty.facultyprofile'),
        ),
    ]
