# Generated by Django 5.2.8 on 2026-07-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0008_alter_batch_max_students_alter_classroom_capacity'),
        ('chat', '0002_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='chat.chatroom'),
        ),
    ]
