# Generated by Django 5.2.5 on 2026-06-10 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0009_alter_batchfaculty_faculty_and_more'),
        ('branch', '0004_remove_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='branch.branch'),
        ),
    ]
