# Generated by Django 6.0.5 on 2026-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0009_auto_chat_room_for_batch'),
        ('faculty', '0002_alter_facultyprofile_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='chapters', to='faculty.facultyprofile'),
        ),
    ]
