# Generated by Django 6.0.5 on 2026-06-11 06:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0009_user_fcm_token'),
        ('batches', '0010_batch_branch'),
        ('faculty', '0003_alter_facultyprofile_employee_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSequenceCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_type', models.CharField(max_length=20)),
                ('batch_attempt', models.CharField(max_length=10)),
                ('attempt_year', models.PositiveSmallIntegerField()),
                ('last_sequence', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'batch_sequence_counters',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subject_chapters',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_levels',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'timetable_exam_types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subjects_course__668b86_idx',
        ),
        migrations.AddField(
            model_name='batch',
            name='attempt_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='auto_sequence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_slots', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='paper_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_slots', to='faculty.facultyprofile'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('class_test', 'Class Test'), ('prelim', 'Prelim'), ('practice', 'Practice'), ('custom', 'Custom')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='slot_code',
            field=models.CharField(blank=True, choices=[('P1', 'P1 08:00–10:00'), ('P2', 'P2 10:15–12:15'), ('P3', 'P3 12:45–14:45'), ('P4', 'P4 15:00–17:00')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='batchsequencecounter',
            unique_together={('course_type', 'batch_attempt', 'attempt_year')},
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='batches.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='batches.chapter'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='batches.course'),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_levels', to='auth_user.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='batches.courselevel'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('level', 'code')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['level', 'is_active'], name='subjects_level_i_74a74f_idx'),
        ),
        migrations.AddField(
            model_name='timetableexamtype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_exam_types', to='auth_user.organization'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='timetable_exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='batches.timetableexamtype'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['session_type'], name='timetable_s_session_88258c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableslot',
            index=models.Index(fields=['session_date'], name='timetable_s_session_b04285_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together={('course', 'order')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
