# Generated by Django 5.1.1 on 2026-09-12 10:11

from django.conf import settings
from django.db import migrations, models


def migrate_faculties_to_users(apps, schema_editor):
    """
    Copy Chapter ↔ FacultyProfile M2M data to Chapter ↔ User M2M.
    Must run BEFORE the AlterField that changes the M2M target.
    We read the old through table directly.
    """
    db_alias = schema_editor.connection.alias
    Chapter = apps.get_model('batches', 'Chapter')
    # Read old M2M rows: the old through table was auto-created by Django
    # for Chapter.faculties -> FacultyProfile
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute(
                "SELECT chapter_id, facultyprofile_id FROM subject_chapters_faculties"
            )
            old_rows = cursor.fetchall()
        except Exception:
            old_rows = []

    if not old_rows:
        return

    # Resolve FacultyProfile -> User mapping
    FacultyProfile = apps.get_model('faculty', 'FacultyProfile')
    fp_to_user = {}
    for fp in FacultyProfile.objects.using(db_alias).select_related().all():
        if fp.user_id:
            fp_to_user[fp.id] = fp.user_id

    # Store mapping for later insertion
    global _chapter_user_pairs
    _chapter_user_pairs = []
    for chapter_id, fp_id in old_rows:
        user_id = fp_to_user.get(fp_id)
        if user_id:
            _chapter_user_pairs.append((chapter_id, user_id))


def insert_user_faculties(apps, schema_editor):
    """
    Insert the Chapter ↔ User M2M data into the NEW through table.
    Must run AFTER the AlterField.
    """
    global _chapter_user_pairs
    pairs = getattr(insert_user_faculties, '_pairs', None) or globals().get('_chapter_user_pairs', [])
    if not pairs:
        return

    with schema_editor.connection.cursor() as cursor:
        for chapter_id, user_id in pairs:
            try:
                cursor.execute(
                    "INSERT OR IGNORE INTO subject_chapters_faculties (chapter_id, user_id) VALUES (%s, %s)",
                    [str(chapter_id), str(user_id)]
                )
            except Exception:
                pass


# Module-level storage for data migration
_chapter_user_pairs = []


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0010_chapter_faculties'),
        ('faculty', '0003_facultyprofile_levels_alter_facultyprofile_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Read old M2M data before the table is dropped
        migrations.RunPython(migrate_faculties_to_users, migrations.RunPython.noop),
        # 2. Alter the field (drops old through table, creates new one)
        migrations.AlterField(
            model_name='chapter',
            name='faculties',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'faculty'}, related_name='faculty_chapters', to=settings.AUTH_USER_MODEL),
        ),
        # 3. Re-insert mapped User IDs into the new through table
        migrations.RunPython(insert_user_faculties, migrations.RunPython.noop),
    ]
