# Generated by Django 6.0.5 on 2026-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0010_notificationhistory'),
        ('batches', '0011_batchsequencecounter_chapter_courselevel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_course__6e31c1_idx',
        ),
        migrations.AddField(
            model_name='courselevel',
            name='course_type',
            field=models.CharField(choices=[('cseet', 'CSEET'), ('cs_executive', 'CS Executive'), ('cs_professional', 'CS Professional')], default='standard', max_length=20),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
