# Generated by Django 5.2.5 on 2026-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0011_chapter_faculties_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='courselevel',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courselevel',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
