# Generated by Django 5.2.5 on 2026-10-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0012_remove_order_required'),
        ('fees', '0007_feestructure_attempt_feestructure_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='fees.feestructure'),
        ),
    ]
