# Generated by Django 6.0.5 on 2026-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0012_remove_course_courses_course__6e31c1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee_amount',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='session',
        ),
        migrations.AddField(
            model_name='courselevel',
            name='duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courselevel',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
