# Generated by Django 6.0.5 on 2026-06-11 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0013_remove_batch_location_remove_course_duration_months_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='paper_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
