# Generated by Django 5.2.5 on 2026-10-03 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0021_user_working_hours'),
        ('batches', '0013_batch_fee_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='batches.courselevel')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='auth_user.organization')),
            ],
            options={
                'db_table': 'syllabuses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='batches.syllabus'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['syllabus', 'is_active'], name='subjects_syllabu_b85bb1_idx'),
        ),
    ]
