# Generated by Django 6.0.5 on 2026-06-12 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0014_alter_timetableslot_examiner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='examiner',
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='paper_checker',
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='timetable_slots', to='batches.chapter'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='examiners',
            field=models.ManyToManyField(blank=True, related_name='examiner_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='paper_checkers',
            field=models.ManyToManyField(blank=True, related_name='checker_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
