# Generated by Django 5.2.5 on 2026-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0014_syllabus_subject_syllabus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
