# Generated by Django 5.2.5 on 2026-10-03 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0015_syllabus_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='syllabus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='batches.syllabus'),
        ),
    ]
