# Generated by Django 6.0.5 on 2026-06-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0015_remove_timetableslot_chapter_and_more'),
        ('exams', '0003_exam_geo_check_interval_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='exam',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slot', to='exams.exam'),
        ),
    ]
