# Generated by Django 5.2.5 on 2026-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0016_batch_syllabus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='group_module',
            field=models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('all', 'All Modules'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module'), ('module_4', '4th Module'), ('module_5', '5th Module')], max_length=20),
        ),
    ]
