# Generated by Django 6.0.5 on 2026-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0017_timetableslot_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='batches/qrcodes/'),
        ),
    ]
