# Generated by Django 6.0.5 on 2026-06-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0018_batch_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableslot',
            name='timetable_exam_type',
        ),
        migrations.DeleteModel(
            name='TimetableExamType',
        ),
    ]
