# Generated by Django 6.0.5 on 2026-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0019_remove_timetableslot_timetable_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
