# Generated by Django 6.0.5 on 2026-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0020_chapter_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='slot_code',
            field=models.CharField(blank=True, choices=[('P1', 'P1 08:00–10:00'), ('P2', 'P2 10:15–12:15'), ('P3', 'P3 12:45–14:45'), ('P4', 'P4 15:00–17:00'), ('P5', 'P5 (Custom Time)'), ('P6', 'P6 (Custom Time)')], max_length=2, null=True),
        ),
    ]
