# Generated by Django 6.0.5 on 2026-07-02 04:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0003_initial'),
        ('branch', '0001_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='branch.branch')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_runs',
                'ordering': ['-year', '-month'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_session_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hour_based_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('absence_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('leave_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('retention_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deduction_note', models.CharField(blank=True, max_length=300)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('attendance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('leave_encashment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=0)),
                ('sessions_conducted', models.IntegerField(default=0)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='faculty.facultyprofile')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_payslips',
            },
        ),
        migrations.CreateModel(
            name='SessionLatePenaltyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.TimeField()),
                ('actual_start', models.TimeField()),
                ('late_minutes', models.IntegerField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grace_applied', models.BooleanField(default=False)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_logs', to='payroll.payslip')),
                ('session_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.sessionreport')),
            ],
            options={
                'db_table': 'payroll_late_penalty_logs',
            },
        ),
        migrations.CreateModel(
            name='ExtraHoursApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payroll_month', models.IntegerField()),
                ('payroll_year', models.IntegerField()),
                ('extra_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours_requests', to='batches.chapter')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours_requests', to='faculty.facultyprofile')),
            ],
            options={
                'db_table': 'payroll_extra_hours_approval',
                'unique_together': {('faculty', 'chapter', 'payroll_month', 'payroll_year')},
            },
        ),
        migrations.CreateModel(
            name='LateEntryPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grace_period_minutes', models.IntegerField(default=5)),
                ('deduction_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_deduction_per_session', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('absence_deduction_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('late_entry_threshold', models.IntegerField(default=3)),
                ('auto_halfday_deduction', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_policies', to='branch.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_late_policies',
                'unique_together': {('branch',)},
            },
        ),
    ]
