# Generated by Django 4.2.29 on 2026-05-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateentrypolicy',
            name='absence_deduction_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='lateentrypolicy',
            name='auto_halfday_deduction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lateentrypolicy',
            name='late_entry_threshold',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='payslip',
            name='absence_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
