# Generated by Django 6.0.5 on 2026-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='late_penalty_minutes',
            field=models.IntegerField(default=0, help_text='Total penalised minutes (after grace) summed across the month'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='per_day_deduction_log',
            field=models.JSONField(blank=True, default=list, help_text='Per-day breakdown: date, late_minutes, penalty_minutes, penalty_amount'),
        ),
    ]
