# Generated by Django 6.0.5 on 2026-06-09 04:49

import django.db.models.deletion
from django.db import migrations, models


def copy_faculty_profile_to_faculty(apps, schema_editor):
    """
    Before we change the faculty FK target from User to FacultyProfile,
    copy the faculty_profile_id into faculty_id so the data is correct.
    """
    PaySlip = apps.get_model('payroll', 'PaySlip')
    for ps in PaySlip.objects.filter(faculty_profile__isnull=False):
        if ps.faculty_profile_id:
            ps.faculty_id = ps.faculty_profile_id
            ps.save(update_fields=['faculty_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_facultyprofile_employee_id'),
        ('payroll', '0002_lateentrypolicy_absence_deduction_per_day_and_more'),
    ]

    operations = [
        # Step 1: Copy faculty_profile_id values into faculty_id
        migrations.RunPython(
            copy_faculty_profile_to_faculty,
            migrations.RunPython.noop,
        ),
        # Step 2: Remove the now-redundant faculty_profile column
        migrations.RemoveField(
            model_name='payslip',
            name='faculty_profile',
        ),
        # Step 3: Alter faculty FK to point to FacultyProfile instead of User
        migrations.AlterField(
            model_name='payslip',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='faculty.facultyprofile'),
        ),
    ]
