# Generated by Django 6.0.5 on 2026-06-20 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0021_alter_timetableslot_slot_code'),
        ('faculty', '0004_facultyqrscanlog_early_minutes_and_more'),
        ('payroll', '0003_fk_consistency_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraHoursApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payroll_month', models.IntegerField()),
                ('payroll_year', models.IntegerField()),
                ('extra_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours_requests', to='batches.chapter')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_hours_requests', to='faculty.facultyprofile')),
            ],
            options={
                'db_table': 'payroll_extra_hours_approval',
                'unique_together': {('faculty', 'chapter', 'payroll_month', 'payroll_year')},
            },
        ),
    ]
