# Generated by Django 5.1.1 on 2026-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_lateentrypolicy_absence_deduction_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='reimbursements_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total approved expense reimbursements added to this payslip', max_digits=12),
        ),
    ]
