# Generated by Django 5.2.8 on 2026-06-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_extrahoursapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='attendance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payslip',
            name='retention_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
