# Generated by Django 5.2.8 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payslip_attendance_bonus_payslip_retention_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='leave_encashment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
