# Generated by Django 4.2.29 on 2026-06-24 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0008_facultyprofile_salary_retention_percentage'),
        ('payroll', '0006_payslip_leave_encashment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='faculty.facultyprofile'),
        ),
    ]
