# Generated by Django 6.0.5 on 2026-07-02 04:58

import django.db.models.deletion
import onboarding.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('fees', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('gen', 'General'), ('obc', 'OBC'), ('sc_st', 'SC/ST')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('email_parent', models.EmailField(max_length=254)),
                ('phone_student', models.CharField(max_length=15)),
                ('phone_student_2', models.CharField(blank=True, max_length=15)),
                ('phone_father', models.CharField(max_length=15)),
                ('phone_father_2', models.CharField(blank=True, max_length=15)),
                ('street', models.TextField()),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('course', models.CharField(choices=[('cseet', 'CSEET'), ('cs_executive', 'CS Executive'), ('cs_professional', 'CS Professional')], max_length=20)),
                ('group_module', models.CharField(choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module')], max_length=20)),
                ('batch_attempt', models.CharField(choices=[('june', 'June'), ('oct', 'October'), ('feb', 'February'), ('dec', 'December')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('appearing_12', 'Appearing 10+2'), ('pass_12', '10+2 Pass or Equivalent'), ('cseet_pass', 'CSEET Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20)),
                ('reference', models.CharField(choices=[('offline_ad', 'Offline Ad'), ('existing', 'Existing Student'), ('social_media', 'Social Media'), ('google', 'Seen on Google'), ('seminar', 'Seminar'), ('none', 'None of the above')], max_length=20)),
                ('consent', models.BooleanField(default=False)),
                ('tenth_medium', models.CharField(choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10)),
                ('tenth_school', models.CharField(max_length=200)),
                ('tenth_coaching', models.CharField(blank=True, max_length=200)),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tenth_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_medium', models.CharField(choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10)),
                ('twelfth_school', models.CharField(max_length=200)),
                ('twelfth_coaching', models.CharField(blank=True, max_length=200)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_percentile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grad_university', models.CharField(blank=True, max_length=200)),
                ('grad_college', models.CharField(blank=True, max_length=200)),
                ('grad_last_sem', models.CharField(blank=True, max_length=200)),
                ('doc_signature', models.FileField(upload_to=onboarding.models.admission_document_path)),
                ('doc_photo', models.FileField(upload_to=onboarding.models.admission_document_path)),
                ('doc_dob_certificate', models.FileField(upload_to=onboarding.models.admission_document_path)),
                ('doc_id_card', models.FileField(upload_to=onboarding.models.admission_document_path)),
                ('doc_twelfth_receipt', models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path)),
                ('doc_twelfth_marksheet', models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path)),
                ('doc_category_cert', models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path)),
                ('attempt_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('form_pending', 'Form Pending'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], default='form_pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Latest note added during status update.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_screenshot', models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path)),
                ('transaction_id', models.CharField(blank=True, help_text='UPI / Bank transaction reference number.', max_length=100)),
                ('payment_note', models.TextField(blank=True, help_text='Optional note from student regarding payment.')),
                ('payment_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the student.', max_digits=10, null=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, help_text='Counsellor assigned to review this admission.', limit_choices_to={'role': 'counsellor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admissions', to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(blank=True, help_text="Bank account assigned for this admission's fee payment (threshold-aware selection).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='fees.bankaccount')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='branch.branch')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='fees.feestructure')),
                ('lead', models.OneToOneField(blank=True, help_text='The inquiry lead this admission originated from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='leads.lead')),
            ],
            options={
                'db_table': 'admissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('form_pending', 'Form Pending'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='onboarding.admission')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status'], name='admissions_status_148dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['course'], name='admissions_course_ba9bae_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['submitted_at'], name='admissions_submitt_a35be3_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['bank_account'], name='admissions_bank_ac_f341ab_idx'),
        ),
    ]
