# Generated by Django 6.0.5 on 2026-05-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='assigned_counsellor',
            field=models.ForeignKey(blank=True, help_text='Counsellor assigned to review this admission.', limit_choices_to={'role': 'counsellor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
