# Generated by Django 6.0.5 on 2026-07-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='group_module',
            field=models.CharField(choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module')], max_length=20),
        ),
    ]
