# Generated by Django 6.0.5 on 2026-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_admission_group_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='reference',
            field=models.CharField(choices=[('offline_ad', 'Offline Ad'), ('existing', 'Existing Student'), ('social_media', 'Social Media'), ('google', 'Seen on Google'), ('seminar', 'Seminar'), ('none', 'None of the above'), ('other', 'Other')], max_length=20),
        ),
    ]
