# Generated by Django 6.0.5 on 2026-07-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_admission_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
