# Generated by Django 6.0.5 on 2026-05-27 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('onboarding', '0003_admission_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='branch.branch'),
        ),
    ]
