# Generated by Django 5.2.8 on 2026-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_admission_reference_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='razorpay_payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='razorpay_payment_link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
