# Generated by Django 6.0.5 on 2026-06-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_admission_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
