# Generated by Django 5.1.1 on 2026-09-03 12:31

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_admission_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='doc_tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
    ]
