# Generated by Django 4.2.29 on 2026-06-06 06:37

from django.db import migrations, models
import onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_admission_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='assigned_bank_id',
            field=models.IntegerField(blank=True, help_text='ID of the bank from BANK_ACCOUNTS assigned to this student.', null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_note',
            field=models.TextField(blank=True, help_text='Optional note from student regarding payment.'),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_screenshot',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='UPI / Bank transaction reference number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20),
        ),
    ]
