# Generated by Django 6.0.5 on 2026-09-15 04:38

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_admission_doc_tenth_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='doc_pan_card',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
    ]
