# Generated by Django 4.2.29 on 2026-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_admission_assigned_bank_id_admission_payment_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('pending', 'Approval Pending'), ('approved', 'Approved'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Approval Pending'), ('approved', 'Approved'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20),
        ),
    ]
