# Generated by Django 6.0.5 on 2026-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_admission_doc_pan_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='icsi_fees_payment',
            field=models.CharField(blank=True, choices=[('pay_yourself', 'Pay Yourself'), ('pay_through_institute', 'Pay through Institute')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('full_payment', 'Full Payment'), ('finance', 'Finance')], max_length=20, null=True),
        ),
    ]
