# Generated by Django 6.0.5 on 2026-06-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_fk_consistency_fix'),
        ('onboarding', '0008_alter_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='attempt_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='fees.feestructure'),
        ),
    ]
