# Generated by Django 6.0.5 on 2026-09-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_admission_icsi_fees_payment_admission_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='qualification',
            field=models.CharField(choices=[('appearing_12', 'Appearing 10+2'), ('pass_12', '10+2 Pass or Equivalent'), ('cseet_pass', 'CSEET Pass'), ('cs_executive_pass', 'CS Executive Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20),
        ),
    ]
