# Generated by Django 6.0.5 on 2026-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_admission_attempt_year_admission_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('form_pending', 'Form Pending'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], default='form_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionstatushistory',
            name='status',
            field=models.CharField(choices=[('form_pending', 'Form Pending'), ('payment_pending', 'Payment Pending'), ('payment_submitted', 'Payment Submitted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], max_length=20),
        ),
    ]
