# Generated by Django 6.0.5 on 2026-09-17 06:35

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0009_alter_admission_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='batch_attempt',
            field=models.CharField(blank=True, choices=[('june', 'June'), ('oct', 'October'), ('feb', 'February'), ('dec', 'December')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='category',
            field=models.CharField(blank=True, choices=[('gen', 'General'), ('obc', 'OBC'), ('sc_st', 'SC/ST')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(blank=True, choices=[('cseet', 'CSEET'), ('cs_executive', 'CS Executive'), ('cs_professional', 'CS Professional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='doc_dob_certificate',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='doc_id_card',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='doc_photo',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='doc_signature',
            field=models.FileField(blank=True, null=True, upload_to=onboarding.models.admission_document_path),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='group_module',
            field=models.CharField(blank=True, choices=[('full', 'Full Syllabus'), ('both', 'Both Modules'), ('module_1', '1st Module'), ('module_2', '2nd Module'), ('module_3', '3rd Module')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='phone_father',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='qualification',
            field=models.CharField(blank=True, choices=[('appearing_12', 'Appearing 10+2'), ('pass_12', '10+2 Pass or Equivalent'), ('cseet_pass', 'CSEET Pass'), ('cs_executive_pass', 'CS Executive Pass'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='reference',
            field=models.CharField(blank=True, choices=[('offline_ad', 'Offline Ad'), ('existing', 'Existing Student'), ('social_media', 'Social Media'), ('google', 'Seen on Google'), ('seminar', 'Seminar'), ('none', 'None of the above'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_medium',
            field=models.CharField(blank=True, choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='tenth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='twelfth_medium',
            field=models.CharField(blank=True, choices=[('gseb', 'Gujarat Board (GSEB)'), ('cbse', 'CBSE Board'), ('icse', 'ICSE Board')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='twelfth_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='twelfth_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='twelfth_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
