# Generated by Django 6.0.5 on 2026-06-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0010_alter_admission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the student.', max_digits=10, null=True),
        ),
    ]
