# Generated by Django 6.0.5 on 2026-06-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_admission_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='assigned_bank_id',
            field=models.CharField(blank=True, help_text='ID of the bank from BANK_ACCOUNTS assigned to this student.', max_length=50, null=True),
        ),
    ]
