# Generated by Django 5.2.8 on 2026-06-29 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_branch_name'),
        ('fees', '0010_add_fee_type_breakdown'),
        ('leads', '0008_alter_lead_current_stage_alter_leadstage_stage'),
        ('onboarding', '0012_alter_admission_assigned_bank_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='assigned_bank_id',
        ),
        migrations.AddField(
            model_name='admission',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Bank account assigned for this admission's fee payment (threshold-aware selection).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='fees.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['bank_account'], name='admissions_bank_ac_f341ab_idx'),
        ),
    ]
