# Generated by Django 6.0.5 on 2026-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='branches/qrcodes/'),
        ),
    ]
