# Generated by Django 4.2.29 on 2026-08-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='allowed_radius_meters',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
