# Generated by Django 6.0.5 on 2026-06-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
    ]
