# Generated by Django 6.0.5 on 2026-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_remove_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allowed_radius_meters',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
