# Generated by Django 4.2.29 on 2026-08-22 11:52

from django.db import migrations


def update_jms_test_coords(apps, schema_editor):
    Branch = apps.get_model('branch', 'Branch')
    Branch.objects.filter(name__icontains='jms test').update(
        latitude=23.01804701952351,
        longitude=72.55508714336585,
    )

def reverse_coords(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_set_coords_and_radius'),
    ]

    operations = [
        migrations.RunPython(update_jms_test_coords, reverse_coords),
    ]
