# Generated by Django 6.0.5 on 2026-06-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_branch_allowed_radius_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
