# Generated by Django 6.0.5 on 2026-05-27 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('branch', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_attendance', 'Low Attendance'), ('absent_streak', 'Absent Streak'), ('checkin_delay_15', 'Check-in Delay 15 min'), ('checkin_delay_30', 'Check-in Delay 30 min'), ('missing_scan', 'Missing Scan'), ('no_checkout', 'No Check-out'), ('violation', 'Violation')], max_length=40)),
                ('message', models.TextField()),
                ('threshold', models.FloatField(blank=True, help_text='e.g. 75.0 for low_attendance alerts', null=True)),
                ('current_pct', models.FloatField(blank=True, help_text='Current attendance percentage when alert was generated.', null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('notified_parent', models.BooleanField(default=False)),
                ('notified_admin', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'db_table': 'attendance_alert_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['student', 'sent_at'], name='attendance__student_cc6f78_idx'), models.Index(fields=['alert_type'], name='attendance__alert_t_56490b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('full_day', 'Full Day')], max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('correction_note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='batches.batch')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='branch.branch')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrected', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(help_text='Faculty or admin who marked this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'session'],
                'indexes': [models.Index(fields=['date', 'branch'], name='attendance__date_e98d6f_idx'), models.Index(fields=['student', 'date'], name='attendance__student_6a013f_idx'), models.Index(fields=['batch', 'date'], name='attendance__batch_i_7882bd_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx')],
                'unique_together': {('student', 'date', 'session', 'batch')},
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scan_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('exam_entry', 'Exam Entry')], max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalid_reason', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='branch.branch')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='students.student')),
            ],
            options={
                'db_table': 'qr_scan_logs',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['student', 'scanned_at'], name='qr_scan_log_student_e9620b_idx'), models.Index(fields=['scan_type'], name='qr_scan_log_scan_ty_a14ae7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViolationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('missing_checkout', 'Missing Check-out'), ('no_show', 'No Show'), ('late_entry', 'Late Entry'), ('missing_scan', 'Missing Scan')], max_length=40)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_resolved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='students.student')),
            ],
            options={
                'db_table': 'attendance_violations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_resolved'], name='attendance__student_b61c8d_idx'), models.Index(fields=['date'], name='attendance__date_eb38f5_idx')],
            },
        ),
    ]
