# Generated by Django 6.0.5 on 2026-05-29 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscanlog',
            name='device_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='violationrecord',
            name='logged_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='alert_type',
            field=models.CharField(choices=[('low_attendance', 'Low Attendance'), ('absent_streak', 'Absent Streak'), ('checkin_delay_15', 'Check-in Delay 15 min'), ('checkin_delay_30', 'Check-in Delay 30 min'), ('missing_checkout_scan', 'Missing Check-out Scan'), ('missing_checkin_scan', 'Missing Check-in Scan'), ('violation', 'Violation')], max_length=40),
        ),
        migrations.AlterField(
            model_name='violationrecord',
            name='violation_type',
            field=models.CharField(choices=[('missing_checkout', 'Missing Check-out'), ('no_show', 'No Show'), ('late_entry', 'Late Entry'), ('missing_checkin_scan', 'Missing Check-in Scan'), ('unauthorised_absence', 'Unauthorised Absence'), ('repeated_delay', 'Repeated Delay')], max_length=40),
        ),
    ]
