# Generated by Django 6.0.5 on 2026-07-15 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('batches', '0008_alter_batch_max_students_alter_classroom_capacity'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='batches.timetableslot'),
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_records', to='batches.timetableslot'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date', 'timetable_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancerecord',
            unique_together={('user', 'date', 'timetable_slot')},
        ),
    ]
