# Generated by Django 6.0.5 on 2026-07-16 09:35
# Custom migration: removed unique_together to support multiple attendance check-in sessions
# per student/employee per date (each check-in gets its own record; no more overwriting check-in time).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('batches', '0001_initial'),  # for TimetableSlot FK
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='timetable_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_records',
                to='batches.timetableslot',
            ),
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='timetable_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employee_attendance_records',
                to='batches.timetableslot',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancerecord',
            unique_together=set(),
        ),
    ]
