# Generated by Django 6.0.5 on 2026-06-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qrscanlog_device_id_violationrecord_created_by_and_more'),
        ('batches', '0010_batch_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrscanlog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='location_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='time_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='timetable_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to='batches.timetableslot'),
        ),
        migrations.AddField(
            model_name='qrscanlog',
            name='validation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
