# Generated by Django 6.0.5 on 2026-07-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_unique_together_and_more'),
        ('attendance', '0002_remove_unique_constraint_multiple_checkins'),
    ]

    operations = [
    ]
