# Generated by Django 6.0.5 on 2026-07-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancerecord',
            unique_together=set(),
        ),
    ]
