# Generated by Django 6.0.5 on 2026-07-16 10:15
# Merge of conflicting 0002 migrations from attendance branches:
# - 0002_alter_attendancerecord_unique_together_and_more.py (added timetable_slot + unique on (student, date, timetable_slot))
# - 0002_remove_unique_constraint_multiple_checkins.py (removed unique_together to support multiple
#   independent check-in sessions per student/date as per v3 FRD for multiple records)
#
# Final state: timetable_slot FK added (nullable), unique_together explicitly removed (empty set)
# to allow multiple AttendanceRecord per (student, date). Latest check-in determined by ordering.
# This supports the new QRScanLog, multiple sessions, timetable_slot linking without constraint violation.

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_unique_together_and_more'),
        ('attendance', '0002_remove_unique_constraint_multiple_checkins'),
        ('batches', '0008_alter_batch_max_students_alter_classroom_capacity'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensure final state has no unique_together (supports multiple checkins per day/slot)
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendancerecord',
            unique_together=set(),
        ),
        # The timetable_slot FK is already added by both predecessor migrations.
        # If any DB inconsistency, this would be handled by Django state.
    ]
