# Generated by Django 6.0.5 on 2026-06-11 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_qrscanlog_latitude_qrscanlog_location_verified_and_more'),
        ('batches', '0011_batchsequencecounter_chapter_courselevel_and_more'),
        ('students', '0004_studentprofile_student_batch_student_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date', 'batch')},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='session',
        ),
    ]
