# Generated by Django 4.2.29 on 2026-08-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendancerecord',
            name='shortfall_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes short of 9-hour shift requirement (0 = met or exempt).'),
        ),
    ]
