# Generated by Django 5.2.5 on 2026-10-05 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_location_to_attendancerecord'),
        ('students', '0003_student_doc_pan_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='violationrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_violations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violationrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='students.student'),
        ),
        migrations.AlterField(
            model_name='violationrecord',
            name='violation_type',
            field=models.CharField(choices=[('missing_checkout', 'Missing Check-out'), ('no_show', 'No Show'), ('late_entry', 'Late Entry'), ('missing_checkin_scan', 'Missing Check-in Scan'), ('unauthorised_absence', 'Unauthorised Absence'), ('repeated_delay', 'Repeated Delay'), ('sales_check_in_selfie', 'Checked in with start selfie'), ('sales_missing_photo', 'Missing Sales Activity Photo')], max_length=40),
        ),
    ]
