# Generated by Django 4.2.29 on 2026-06-24 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0006_alter_branch_name'),
        ('attendance', '0005_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('checkout_pending', 'Checkout Pending')], default='absent', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('correction_note', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_records', to='branch.branch')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_corrected', to=settings.AUTH_USER_MODEL)),
                ('marked_by', models.ForeignKey(help_text='Admin who marked this record (null for self-scan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_attendance_records',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'branch'], name='employee_at_date_e39855_idx'), models.Index(fields=['user', 'date'], name='employee_at_user_id_34cbe7_idx'), models.Index(fields=['status'], name='employee_at_status_79898c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
